// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package repository

import (
	"context"
)

const deleteBudgetByUser = `-- name: DeleteBudgetByUser :exec
DELETE FROM app.budgets
WHERE user_id = $1
`

func (q *Queries) DeleteBudgetByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBudgetByUser, userID)
	return err
}

const getHolidays = `-- name: GetHolidays :one
SELECT holidays
FROM app.budgets
WHERE user_id = $1
`

func (q *Queries) GetHolidays(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getHolidays, userID)
	var holidays string
	err := row.Scan(&holidays)
	return holidays, err
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO app.budgets (user_id, holidays)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET holidays = EXCLUDED.holidays
`

type UpsertBudgetParams struct {
	UserID   int64
	Holidays string
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertBudget, arg.UserID, arg.Holidays)
	return err
}
