// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :execrows
INSERT INTO app.entries (user_id, amount_remaining, date)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, date) DO NOTHING
`

type CreateEntryParams struct {
	UserID          int64
	AmountRemaining float64
	Date            pgtype.Date
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEntry, arg.UserID, arg.AmountRemaining, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEntriesByUser = `-- name: DeleteEntriesByUser :exec
DELETE FROM app.entries
WHERE user_id = $1
`

func (q *Queries) DeleteEntriesByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEntriesByUser, userID)
	return err
}

const listEntries = `-- name: ListEntries :many
SELECT amount_remaining, date
FROM app.entries
WHERE user_id = $1
ORDER BY date DESC
`

type ListEntriesRow struct {
	AmountRemaining float64
	Date            pgtype.Date
}

func (q *Queries) ListEntries(ctx context.Context, userID int64) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(&i.AmountRemaining, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
