// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Entry struct {
	ID              int64
	AmountRemaining float64
	Date            pgtype.Date
	TermID          int64
}

type Term struct {
	ID        int64
	UserID    int64
	Name      string
	EndDate   pgtype.Date
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type TermDaysOff struct {
	TermID int64
	Date   pgtype.Date
}

type User struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
}
