// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID       int64
	UserID   int64
	Holidays string
}

type Entry struct {
	ID              int64
	UserID          int64
	AmountRemaining float64
	Date            pgtype.Date
}

type User struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
}
