// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActiveTerm = `-- name: CreateActiveTerm :one
INSERT INTO app.terms (user_id, name, end_date, is_active)
VALUES ($1, $2, $3, true)
RETURNING id
`

type CreateActiveTermParams struct {
	UserID  int64
	Name    string
	EndDate pgtype.Date
}

func (q *Queries) CreateActiveTerm(ctx context.Context, arg CreateActiveTermParams) (int64, error) {
	row := q.db.QueryRow(ctx, createActiveTerm, arg.UserID, arg.Name, arg.EndDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteActiveTermByUser = `-- name: DeleteActiveTermByUser :exec
DELETE FROM app.terms
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) DeleteActiveTermByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteActiveTermByUser, userID)
	return err
}

const deleteDaysOffByTerm = `-- name: DeleteDaysOffByTerm :exec
DELETE FROM app.term_days_off
WHERE term_id = $1
`

func (q *Queries) DeleteDaysOffByTerm(ctx context.Context, termID int64) error {
	_, err := q.db.Exec(ctx, deleteDaysOffByTerm, termID)
	return err
}

const getActiveTerm = `-- name: GetActiveTerm :one
SELECT id, user_id, name, end_date, is_active, created_at
FROM app.terms
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) GetActiveTerm(ctx context.Context, userID int64) (Term, error) {
	row := q.db.QueryRow(ctx, getActiveTerm, userID)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertDayOff = `-- name: InsertDayOff :exec
INSERT INTO app.term_days_off (term_id, date)
VALUES ($1, $2)
`

type InsertDayOffParams struct {
	TermID int64
	Date   pgtype.Date
}

func (q *Queries) InsertDayOff(ctx context.Context, arg InsertDayOffParams) error {
	_, err := q.db.Exec(ctx, insertDayOff, arg.TermID, arg.Date)
	return err
}

const listDaysOff = `-- name: ListDaysOff :many
SELECT date
FROM app.term_days_off
WHERE term_id = $1
ORDER BY date
`

func (q *Queries) ListDaysOff(ctx context.Context, termID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDaysOff, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveTerm = `-- name: UpdateActiveTerm :exec
UPDATE app.terms
SET name = $2
WHERE id = $1
`

type UpdateActiveTermParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateActiveTerm(ctx context.Context, arg UpdateActiveTermParams) error {
	_, err := q.db.Exec(ctx, updateActiveTerm, arg.ID, arg.Name)
	return err
}
