// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTerm = `-- name: ActivateTerm :one
UPDATE app.terms
SET is_active = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, end_date, is_active, created_at
`

type ActivateTermParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) ActivateTerm(ctx context.Context, arg ActivateTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, activateTerm, arg.ID, arg.UserID)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTerm = `-- name: CreateTerm :one
INSERT INTO app.terms (user_id, name, end_date, is_active)
VALUES ($1, $2, $3, false)
RETURNING id, user_id, name, end_date, is_active, created_at
`

type CreateTermParams struct {
	UserID  int64
	Name    string
	EndDate pgtype.Date
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, createTerm, arg.UserID, arg.Name, arg.EndDate)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateTermsByUser = `-- name: DeactivateTermsByUser :exec
UPDATE app.terms
SET is_active = false
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) DeactivateTermsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deactivateTermsByUser, userID)
	return err
}

const deleteDaysOffByTerm = `-- name: DeleteDaysOffByTerm :exec
DELETE FROM app.term_days_off
WHERE term_id = $1
`

func (q *Queries) DeleteDaysOffByTerm(ctx context.Context, termID int64) error {
	_, err := q.db.Exec(ctx, deleteDaysOffByTerm, termID)
	return err
}

const deleteTermsByUser = `-- name: DeleteTermsByUser :exec
DELETE FROM app.terms
WHERE user_id = $1
`

func (q *Queries) DeleteTermsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteTermsByUser, userID)
	return err
}

const getOrCreateActiveTerm = `-- name: GetOrCreateActiveTerm :one
INSERT INTO app.terms (user_id, name, end_date, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (user_id) WHERE is_active = true DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, name, end_date, is_active, created_at
`

type GetOrCreateActiveTermParams struct {
	UserID  int64
	Name    string
	EndDate pgtype.Date
}

func (q *Queries) GetOrCreateActiveTerm(ctx context.Context, arg GetOrCreateActiveTermParams) (Term, error) {
	row := q.db.QueryRow(ctx, getOrCreateActiveTerm, arg.UserID, arg.Name, arg.EndDate)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTermByID = `-- name: GetTermByID :one
SELECT id, user_id, name, end_date, is_active, created_at
FROM app.terms
WHERE id = $1 AND user_id = $2
`

type GetTermByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTermByID(ctx context.Context, arg GetTermByIDParams) (Term, error) {
	row := q.db.QueryRow(ctx, getTermByID, arg.ID, arg.UserID)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertDayOff = `-- name: InsertDayOff :exec
INSERT INTO app.term_days_off (term_id, date)
VALUES ($1, $2)
`

type InsertDayOffParams struct {
	TermID int64
	Date   pgtype.Date
}

func (q *Queries) InsertDayOff(ctx context.Context, arg InsertDayOffParams) error {
	_, err := q.db.Exec(ctx, insertDayOff, arg.TermID, arg.Date)
	return err
}

const listDaysOff = `-- name: ListDaysOff :many
SELECT date
FROM app.term_days_off
WHERE term_id = $1
ORDER BY date
`

func (q *Queries) ListDaysOff(ctx context.Context, termID int64) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listDaysOff, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerms = `-- name: ListTerms :many
SELECT id, user_id, name, end_date, is_active, created_at
FROM app.terms
WHERE user_id = $1
ORDER BY end_date
`

func (q *Queries) ListTerms(ctx context.Context, userID int64) ([]Term, error) {
	rows, err := q.db.Query(ctx, listTerms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Term
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveTerm = `-- name: UpdateActiveTerm :exec
UPDATE app.terms
SET name = $2, end_date = $3
WHERE id = $1
`

type UpdateActiveTermParams struct {
	ID      int64
	Name    string
	EndDate pgtype.Date
}

func (q *Queries) UpdateActiveTerm(ctx context.Context, arg UpdateActiveTermParams) error {
	_, err := q.db.Exec(ctx, updateActiveTerm, arg.ID, arg.Name, arg.EndDate)
	return err
}
