// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO app.users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id
`

func (q *Queries) GetOrCreateUser(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}
