CREATE SCHEMA app;

CREATE TABLE app.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE app.budgets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    holidays jsonb NOT NULL,
    CONSTRAINT budgets_pkey PRIMARY KEY (id),
    CONSTRAINT budgets_user_id_key UNIQUE (user_id),
    CONSTRAINT budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES app.users (id)
);

CREATE TABLE app.entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    amount_remaining double precision NOT NULL,
    date date NOT NULL,
    CONSTRAINT entries_pkey PRIMARY KEY (id),
    CONSTRAINT entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES app.users (id),
    CONSTRAINT entries_user_id_date_key UNIQUE (user_id, date)
);
