CREATE TABLE app.terms (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    name text NOT NULL,
    end_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT terms_pkey PRIMARY KEY (id),
    CONSTRAINT terms_user_id_fkey FOREIGN KEY (user_id) REFERENCES app.users (id),
    CONSTRAINT terms_user_id_name_key UNIQUE (user_id, name)
);

CREATE UNIQUE INDEX terms_one_active_per_user
    ON app.terms (user_id) WHERE is_active = true;

CREATE TABLE app.term_days_off (
    term_id bigint NOT NULL,
    date date NOT NULL,
    CONSTRAINT term_days_off_pkey PRIMARY KEY (term_id, date),
    CONSTRAINT term_days_off_term_id_fkey FOREIGN KEY (term_id) REFERENCES app.terms (id) ON DELETE CASCADE
);

INSERT INTO app.terms (user_id, name, end_date, is_active)
SELECT user_id, 'Spring 2026', '2026-05-23'::date, true
FROM app.budgets;

INSERT INTO app.term_days_off (term_id, date)
SELECT t.id, elem::date
FROM app.budgets b
JOIN app.terms t ON t.user_id = b.user_id
CROSS JOIN LATERAL jsonb_array_elements_text(b.holidays) AS elem;

DROP TABLE app.budgets;
