


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."flex_budgets" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "holidays" "jsonb" NOT NULL
);


ALTER TABLE "public"."flex_budgets" OWNER TO "postgres";


ALTER TABLE "public"."flex_budgets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flex_budgets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."flex_entries" (
    "id" bigint NOT NULL,
    "amount_remaining" double precision NOT NULL,
    "date" "date" NOT NULL,
    "user_id" bigint NOT NULL
);


ALTER TABLE "public"."flex_entries" OWNER TO "postgres";


ALTER TABLE "public"."flex_entries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flex_entries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."flex_users" (
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."flex_users" OWNER TO "postgres";


ALTER TABLE "public"."flex_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flex_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."flex_budgets"
    ADD CONSTRAINT "flex_budgets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flex_budgets"
    ADD CONSTRAINT "flex_budgets_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."flex_entries"
    ADD CONSTRAINT "flex_entries_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."flex_entries"
    ADD CONSTRAINT "flex_entries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flex_users"
    ADD CONSTRAINT "flex_users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."flex_users"
    ADD CONSTRAINT "flex_users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."flex_users"
    ADD CONSTRAINT "flex_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flex_budgets"
    ADD CONSTRAINT "flex_budgets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."flex_users"("id");



ALTER TABLE ONLY "public"."flex_entries"
    ADD CONSTRAINT "flex_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."flex_users"("id");



CREATE POLICY "Enable read access for all users" ON "public"."flex_entries" FOR SELECT USING (true);



ALTER TABLE "public"."flex_budgets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."flex_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."flex_users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."flex_budgets" TO "anon";
GRANT ALL ON TABLE "public"."flex_budgets" TO "authenticated";
GRANT ALL ON TABLE "public"."flex_budgets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."flex_budgets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flex_budgets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flex_budgets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."flex_entries" TO "anon";
GRANT ALL ON TABLE "public"."flex_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."flex_entries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."flex_entries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flex_entries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flex_entries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."flex_users" TO "anon";
GRANT ALL ON TABLE "public"."flex_users" TO "authenticated";
GRANT ALL ON TABLE "public"."flex_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."flex_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flex_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flex_users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


